import '../entities/trip.dart';

class TripModel extends TripResponse {
  TripModel({
    super.totalSize,
    super.limit,
    super.offset,
    super.orders,
  });

  factory TripModel.fromJson(Map<String, dynamic> json) {
    return TripModel(
      totalSize: json['total_size'],
      limit: json['limit']?.toString(),
      offset: json['offset']?.toString(),
      orders: json['orders'] != null ? Orders.fromJson(json['orders']) : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'total_size': totalSize,
      'limit': limit,
      'offset': offset,
      'orders': orders != null ? (orders as Orders).toJson() : null,
    };
  }
}

class Orders extends TripOrdersEntity {
  Orders({
    super.currentPage,
    super.data,
    super.firstPageUrl,
    super.from,
    super.lastPage,
    super.lastPageUrl,
    super.nextPageUrl,
    super.path,
    super.perPage,
    super.prevPageUrl,
    super.to,
    super.total,
  });

  factory Orders.fromJson(Map<String, dynamic> json) {
    return Orders(
      currentPage: json['current_page'],
      data: json['data'] != null ? (json['data'] as List).map((v) => Data.fromJson(v)).toList() : null,
      firstPageUrl: json['first_page_url'],
      from: json['from'],
      lastPage: json['last_page'],
      lastPageUrl: json['last_page_url'],
      nextPageUrl: json['next_page_url'],
      path: json['path'],
      perPage: json['per_page']?.toString(),
      prevPageUrl: json['prev_page_url'],
      to: json['to'],
      total: json['total'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'current_page': currentPage,
      'data': data?.map((v) => (v as Data).toJson()).toList(),
      'first_page_url': firstPageUrl,
      'from': from,
      'last_page': lastPage,
      'last_page_url': lastPageUrl,
      'next_page_url': nextPageUrl,
      'path': path,
      'per_page': perPage,
      'prev_page_url': prevPageUrl,
      'to': to,
      'total': total,
    };
  }
}

class Data extends TripDataEntity {
  Data({
    super.id,
    super.userId,
    super.orderAmount,
    super.couponDiscountAmount,
    super.couponDiscountTitle,
    super.paymentStatus,
    super.orderStatus,
    super.totalTaxAmount,
    super.paymentMethod,
    super.transactionReference,
    super.deliveryAddressId,
    super.deliveryManId,
    super.couponCode,
    super.orderNote,
    super.orderType,
    super.checked,
    super.storeId,
    super.createdAt,
    super.updatedAt,
    super.deliveryCharge,
    super.scheduleAt,
    super.callback,
    super.otp,
    super.pending,
    super.accepted,
    super.confirmed,
    super.processing,
    super.handover,
    super.pickedUp,
    super.delivered,
    super.canceled,
    super.refundRequested,
    super.refunded,
    super.deliveryAddress,
    super.scheduled,
    super.storeDiscountAmount,
    super.originalDeliveryCharge,
    super.failed,
    super.adjusment,
    super.edited,
    super.deliveryTime,
    super.zoneId,
    super.moduleId,
    super.orderAttachment,
    super.distance,
    super.parcelCategoryId,
    super.receiverDetails,
    super.chargePayer,
    super.dmTips,
    super.freeDeliveryBy,
    super.refundRequestCanceled,
    super.prescriptionOrder,
    super.taxStatus,
    super.tripOrder,
    super.operationAreaId,
    super.providerId,
    super.moduleType,
    super.provider,
    super.trip,
    super.customer,
    super.module,
  });

  factory Data.fromJson(Map<String, dynamic> json) {
    return Data(
      id: json['id'],
      userId: json['user_id'],
      orderAmount: json['order_amount']?.toDouble(),
      couponDiscountAmount: json['coupon_discount_amount']?.toDouble(),
      couponDiscountTitle: json['coupon_discount_title'],
      paymentStatus: json['payment_status'],
      orderStatus: json['order_status'],
      totalTaxAmount: json['total_tax_amount']?.toDouble(),
      paymentMethod: json['payment_method'],
      transactionReference: json['transaction_reference'],
      deliveryAddressId: json['delivery_address_id'],
      deliveryManId: json['delivery_man_id'],
      couponCode: json['coupon_code'],
      orderNote: json['order_note'],
      orderType: json['order_type'],
      checked: json['checked'],
      storeId: json['store_id'],
      createdAt: json['created_at'],
      updatedAt: json['updated_at'],
      deliveryCharge: json['delivery_charge'],
      scheduleAt: json['schedule_at'],
      callback: json['callback'],
      otp: json['otp'],
      pending: json['pending'],
      accepted: json['accepted'],
      confirmed: json['confirmed'],
      processing: json['processing'],
      handover: json['handover'],
      pickedUp: json['picked_up'],
      delivered: json['delivered'],
      canceled: json['canceled'],
      refundRequested: json['refund_requested'],
      refunded: json['refunded'],
      deliveryAddress: json['delivery_address'],
      scheduled: json['scheduled'],
      storeDiscountAmount: json['store_discount_amount'],
      originalDeliveryCharge: json['original_delivery_charge'],
      failed: json['failed'],
      adjusment: json['adjusment'],
      edited: json['edited'],
      deliveryTime: json['delivery_time'],
      zoneId: json['zone_id']?.toString(),
      moduleId: json['module_id'],
      orderAttachment: json['order_attachment'],
      distance: json['distance']?.toDouble(),
      parcelCategoryId: json['parcel_category_id'],
      receiverDetails: json['receiver_details'],
      chargePayer: json['charge_payer'],
      dmTips: json['dm_tips'],
      freeDeliveryBy: json['free_delivery_by'],
      refundRequestCanceled: json['refund_request_canceled'],
      prescriptionOrder: json['prescription_order'],
      taxStatus: json['tax_status'],
      tripOrder: json['trip_order'],
      operationAreaId: json['operation_area_id'],
      providerId: json['provider_id'],
      moduleType: json['module_type'],
      provider: json['provider'] != null ? Provider.fromJson(json['provider']) : null,
      trip: json['trip'] != null ? Trip.fromJson(json['trip']) : null,
      customer: json['customer'] != null ? Customer.fromJson(json['customer']) : null,
      module: json['module'] != null ? Module.fromJson(json['module']) : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'user_id': userId,
      'order_amount': orderAmount,
      'coupon_discount_amount': couponDiscountAmount,
      'coupon_discount_title': couponDiscountTitle,
      'payment_status': paymentStatus,
      'order_status': orderStatus,
      'total_tax_amount': totalTaxAmount,
      'payment_method': paymentMethod,
      'transaction_reference': transactionReference,
      'delivery_address_id': deliveryAddressId,
      'delivery_man_id': deliveryManId,
      'coupon_code': couponCode,
      'order_note': orderNote,
      'order_type': orderType,
      'checked': checked,
      'store_id': storeId,
      'created_at': createdAt,
      'updated_at': updatedAt,
      'delivery_charge': deliveryCharge,
      'schedule_at': scheduleAt,
      'callback': callback,
      'otp': otp,
      'pending': pending,
      'accepted': accepted,
      'confirmed': confirmed,
      'processing': processing,
      'handover': handover,
      'picked_up': pickedUp,
      'delivered': delivered,
      'canceled': canceled,
      'refund_requested': refundRequested,
      'refunded': refunded,
      'delivery_address': deliveryAddress,
      'scheduled': scheduled,
      'store_discount_amount': storeDiscountAmount,
      'original_delivery_charge': originalDeliveryCharge,
      'failed': failed,
      'adjusment': adjusment,
      'edited': edited,
      'delivery_time': deliveryTime,
      'zone_id': zoneId,
      'module_id': moduleId,
      'order_attachment': orderAttachment,
      'distance': distance,
      'parcel_category_id': parcelCategoryId,
      'receiver_details': receiverDetails,
      'charge_payer': chargePayer,
      'dm_tips': dmTips,
      'free_delivery_by': freeDeliveryBy,
      'refund_request_canceled': refundRequestCanceled,
      'prescription_order': prescriptionOrder,
      'tax_status': taxStatus,
      'trip_order': tripOrder,
      'operation_area_id': operationAreaId,
      'provider_id': providerId,
      'module_type': moduleType,
      'provider': provider != null ? (provider as Provider).toJson() : null,
      'trip': trip != null ? (trip as Trip).toJson() : null,
      'customer': customer != null ? (customer as Customer).toJson() : null,
      'module': module != null ? (module as Module).toJson() : null,
    };
  }
}

class Provider extends TripProviderEntity {
  Provider({
    super.id,
    super.name,
    super.phone,
    super.email,
    super.logo,
    super.coverPhoto,
    super.latitude,
    super.longitude,
    super.address,
    super.footerText,
    super.tax,
    super.comission,
    super.currency,
    super.status,
    super.totalVehicle,
    super.totalDriver,
    super.totalTrip,
    super.completedTrip,
    super.ongoingTrip,
    super.canceledTrip,
    super.vendorId,
    super.moduleId,
    super.operationAreaId,
    super.createdAt,
    super.updatedAt,
  });

  factory Provider.fromJson(Map<String, dynamic> json) {
    return Provider(
      id: json['id'],
      name: json['name'],
      phone: json['phone'],
      email: json['email'],
      logo: json['logo'],
      coverPhoto: json['cover_photo'],
      latitude: json['latitude'],
      longitude: json['longitude'],
      address: json['address'],
      footerText: json['footer_text'],
      tax: json['tax'],
      comission: json['comission'],
      currency: json['currency'],
      status: json['status'],
      totalVehicle: json['total_vehicle'],
      totalDriver: json['total_driver'],
      totalTrip: json['total_trip'],
      completedTrip: json['completed_trip'],
      ongoingTrip: json['ongoing_trip'],
      canceledTrip: json['canceled_trip'],
      vendorId: json['vendor_id'],
      moduleId: json['module_id'],
      operationAreaId: json['operation_area_id'],
      createdAt: json['created_at'],
      updatedAt: json['updated_at'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'phone': phone,
      'email': email,
      'logo': logo,
      'cover_photo': coverPhoto,
      'latitude': latitude,
      'longitude': longitude,
      'address': address,
      'footer_text': footerText,
      'tax': tax,
      'comission': comission,
      'currency': currency,
      'status': status,
      'total_vehicle': totalVehicle,
      'total_driver': totalDriver,
      'total_trip': totalTrip,
      'completed_trip': completedTrip,
      'ongoing_trip': ongoingTrip,
      'canceled_trip': canceledTrip,
      'vendor_id': vendorId,
      'module_id': moduleId,
      'operation_area_id': operationAreaId,
      'created_at': createdAt,
      'updated_at': updatedAt,
    };
  }
}

class Trip extends TripDetailsEntity {
  Trip({
    super.id,
    super.orderId,
    super.userId,
    super.vehicleId,
    super.driverId,
    super.providerId,
    super.moduleId,
    super.operationAreaId,
    super.vehicleCategory,
    super.tripAmount,
    super.couponDiscountAmount,
    super.couponDiscountTitle,
    super.paymentStatus,
    super.tripStatus,
    super.totalTaxAmount,
    super.paymentMethod,
    super.transactionReference,
    super.couponCode,
    super.additionalNote,
    super.checked,
    super.additionalCharge,
    super.cancelationFare,
    super.estimatedFare,
    super.estimatedTime,
    super.estimatedDistance,
    super.actualFare,
    super.actualTime,
    super.actualDistance,
    super.scheduleAt,
    super.scheduled,
    super.otp,
    super.pending,
    super.accepted,
    super.confirmed,
    super.outForPickup,
    super.arrived,
    super.onTheWay,
    super.dropped,
    super.canceled,
    super.rejected,
    super.failed,
    super.providerDiscountAmount,
    super.createdAt,
    super.updatedAt,
  });

  factory Trip.fromJson(Map<String, dynamic> json) {
    return Trip(
      id: json['id'],
      orderId: json['order_id'],
      userId: json['user_id'],
      vehicleId: json['vehicle_id'],
      driverId: json['driver_id'],
      providerId: json['provider_id'],
      moduleId: json['module_id'],
      operationAreaId: json['operation_area_id'],
      vehicleCategory: json['vehicle_category'],
      tripAmount: json['trip_amount'] != null ? double.parse(json['trip_amount'].toString()) : null,
      couponDiscountAmount: json['coupon_discount_amount']?.toDouble(),
      couponDiscountTitle: json['coupon_discount_title'],
      paymentStatus: json['payment_status'],
      tripStatus: json['trip_status'],
      totalTaxAmount: json['total_tax_amount']?.toDouble(),
      paymentMethod: json['payment_method'],
      transactionReference: json['transaction_reference'],
      couponCode: json['coupon_code'],
      additionalNote: json['additional_note'],
      checked: json['checked'],
      additionalCharge: json['additional_charge'],
      cancelationFare: json['cancelation_fare'],
      estimatedFare: json['estimated_fare']?.toDouble(),
      estimatedTime: json['estimated_time']?.toDouble(),
      estimatedDistance: json['estimated_distance']?.toDouble(),
      actualFare: json['actual_fare']?.toDouble(),
      actualTime: json['actual_time']?.toDouble(),
      actualDistance: json['actual_distance']?.toDouble(),
      scheduleAt: json['schedule_at'],
      scheduled: json['scheduled'],
      otp: json['otp'],
      pending: json['pending'],
      accepted: json['accepted'],
      confirmed: json['confirmed'],
      outForPickup: json['out_for_pickup'],
      arrived: json['arrived'],
      onTheWay: json['on_the_way'],
      dropped: json['dropped'],
      canceled: json['canceled'],
      rejected: json['rejected'],
      failed: json['failed'],
      providerDiscountAmount: json['provider_discount_amount']?.toDouble(),
      createdAt: json['created_at'],
      updatedAt: json['updated_at'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'order_id': orderId,
      'user_id': userId,
      'vehicle_id': vehicleId,
      'driver_id': driverId,
      'provider_id': providerId,
      'module_id': moduleId,
      'operation_area_id': operationAreaId,
      'vehicle_category': vehicleCategory,
      'trip_amount': tripAmount,
      'coupon_discount_amount': couponDiscountAmount,
      'coupon_discount_title': couponDiscountTitle,
      'payment_status': paymentStatus,
      'trip_status': tripStatus,
      'total_tax_amount': totalTaxAmount,
      'payment_method': paymentMethod,
      'transaction_reference': transactionReference,
      'coupon_code': couponCode,
      'additional_note': additionalNote,
      'checked': checked,
      'additional_charge': additionalCharge,
      'cancelation_fare': cancelationFare,
      'estimated_fare': estimatedFare,
      'estimated_time': estimatedTime,
      'estimated_distance': estimatedDistance,
      'actual_fare': actualFare,
      'actual_time': actualTime,
      'actual_distance': actualDistance,
      'schedule_at': scheduleAt,
      'scheduled': scheduled,
      'otp': otp,
      'pending': pending,
      'accepted': accepted,
      'confirmed': confirmed,
      'out_for_pickup': outForPickup,
      'arrived': arrived,
      'on_the_way': onTheWay,
      'dropped': dropped,
      'canceled': canceled,
      'rejected': rejected,
      'failed': failed,
      'provider_discount_amount': providerDiscountAmount,
      'created_at': createdAt,
      'updated_at': updatedAt,
    };
  }
}

class Customer extends TripCustomerEntity {
  Customer({
    super.id,
    super.fName,
    super.lName,
    super.phone,
    super.email,
    super.image,
    super.isPhoneVerified,
    super.emailVerifiedAt,
    super.createdAt,
    super.updatedAt,
    super.cmFirebaseToken,
    super.status,
    super.orderCount,
    super.loginMedium,
    super.socialId,
    super.zoneId,
    super.walletBalance,
    super.loyaltyPoint,
    super.refCode,
    super.currentLanguageKey,
  });

  factory Customer.fromJson(Map<String, dynamic> json) {
    return Customer(
      id: json['id'],
      fName: json['f_name'],
      lName: json['l_name'],
      phone: json['phone'],
      email: json['email'],
      image: json['image'],
      isPhoneVerified: json['is_phone_verified'],
      emailVerifiedAt: json['email_verified_at'],
      createdAt: json['created_at'],
      updatedAt: json['updated_at'],
      cmFirebaseToken: json['cm_firebase_token'],
      status: json['status'],
      orderCount: json['order_count'],
      loginMedium: json['login_medium'],
      socialId: json['social_id'],
      zoneId: json['zone_id'],
      walletBalance: json['wallet_balance']?.toDouble(),
      loyaltyPoint: json['loyalty_point'],
      refCode: json['ref_code'],
      currentLanguageKey: json['current_language_key'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'f_name': fName,
      'l_name': lName,
      'phone': phone,
      'email': email,
      'image': image,
      'is_phone_verified': isPhoneVerified,
      'email_verified_at': emailVerifiedAt,
      'created_at': createdAt,
      'updated_at': updatedAt,
      'cm_firebase_token': cmFirebaseToken,
      'status': status,
      'order_count': orderCount,
      'login_medium': loginMedium,
      'social_id': socialId,
      'zone_id': zoneId,
      'wallet_balance': walletBalance,
      'loyalty_point': loyaltyPoint,
      'ref_code': refCode,
      'current_language_key': currentLanguageKey,
    };
  }
}

class Module extends TripModuleEntity {
  Module({
    super.id,
    super.moduleName,
    super.moduleType,
    super.thumbnail,
    super.status,
    super.storesCount,
    super.createdAt,
    super.updatedAt,
    super.icon,
    super.themeId,
    super.description,
    super.allZoneService,
  });

  factory Module.fromJson(Map<String, dynamic> json) {
    return Module(
      id: json['id'],
      moduleName: json['module_name'],
      moduleType: json['module_type'],
      thumbnail: json['thumbnail'],
      status: json['status']?.toString(),
      storesCount: json['stores_count'],
      createdAt: json['created_at'],
      updatedAt: json['updated_at'],
      icon: json['icon'],
      themeId: json['theme_id'],
      description: json['description'],
      allZoneService: json['all_zone_service'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'module_name': moduleName,
      'module_type': moduleType,
      'thumbnail': thumbnail,
      'status': status,
      'stores_count': storesCount,
      'created_at': createdAt,
      'updated_at': updatedAt,
      'icon': icon,
      'theme_id': themeId,
      'description': description,
      'all_zone_service': allZoneService,
    };
  }
}