// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqCaD2TuLbvgnYhou_HwbnVnbY6H9Jv94',
    appId: '1:795270039501:web:6df15485e65f7b476e2684',
    messagingSenderId: '795270039501',
    projectId: 'flat-33157',
    authDomain: 'flat-33157.firebaseapp.com',
    storageBucket: 'flat-33157.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Jfv7yFlSI1qryX3SLYryIbSapEU2-7g',
    appId: '1:795270039501:android:49430289b19f14f46e2684',
    messagingSenderId: '795270039501',
    projectId: 'flat-33157',
    storageBucket: 'flat-33157.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChatvd5BSSeWx8o6jUl1A8sGjPr7l6Shs',
    appId: '1:795270039501:ios:d57abf357a1e148a6e2684',
    messagingSenderId: '795270039501',
    projectId: 'flat-33157',
    storageBucket: 'flat-33157.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChatvd5BSSeWx8o6jUl1A8sGjPr7l6Shs',
    appId: '1:795270039501:ios:d57abf357a1e148a6e2684',
    messagingSenderId: '795270039501',
    projectId: 'flat-33157',
    storageBucket: 'flat-33157.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqCaD2TuLbvgnYhou_HwbnVnbY6H9Jv94',
    appId: '1:795270039501:web:f3b5a25d6359afa46e2684',
    messagingSenderId: '795270039501',
    projectId: 'flat-33157',
    authDomain: 'flat-33157.firebaseapp.com',
    storageBucket: 'flat-33157.firebasestorage.app',
  );
}
